depth: 16
nqubit: 6
gate:
  type: "indirect_xy"
  parametric_rotation_gate_set: 4
  max_time: 10
  constraints: ""
  bn:
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0]
  cn:
    type: "static"
    value: [1.0,1.0,1.0,1.0,1.0,1.0]
  r:
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0]
