depth: 20
nqubit: 8
gate:
  type: "indirect_xy"
  parametric_rotation_gate_set: 4
  max_time: 10
  constraints: ""
  bn:
    type: "static_random"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
  cn:
    type: "static"
    value: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  r:
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
