depth: 4
nqubit: 7
gate:
  type: "direct"
  parametric_rotation_gate_set: 3
  constraints: ""
  bounds: False
  noise:
    singlequbit:
      enabled: False
      value: None
    twoqubit:
      enabled: True
      value: 0.001
  bn:
    type: "static"
  cn:
    type: "static"
  r:
    type: "static"
