depth: 12
nqubit: 4
optimize:
  method: "SLSQP"
gate:
  type: "indirect_xy"
  parametric_rotation_gate_set: 4
  constraints: False
  bounds: False
  noise:
    singlequbit:
      enabled: False
      value: None
    twoqubit:
      enabled: False
      value: None
  time:
    type: "random"
    min_val: -3
    max_val: 3
  bn:
    # type: "static_random"
    # range: 1
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
  cn:
    type: "static"
    value: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  r:
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
gcp:
  project:
    id: "anan-project"
  bigquery:
    import: False
