depth: 12
nqubit: 7
gate:
  type: "indirect_xy"
  parametric_rotation_gate_set: 4
  constraints: False
  bounds: True
  time:
    type: "random"
    min_val: -3
    max_val: 3
  bn:
    # type: "static_random"
    # range: 1
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
  cn:
    type: "static"
    value: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  r:
    type: "static"
    value: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
