depth: 12
nqubit: 3
gate:
  type: "direct"
  parametric_rotation_gate_set: 3
  constraints: ""
  bounds: False
  noise:
    singlequbit:
      enabled: False
      value: None
    twoqubit:
      enabled: False
      value: None
  bn:
    type: "static"
  cn:
    type: "static"
  r:
    type: "static"
